### ISSUE TITLE
Nextra not working from next export

### ISSUE THREAD

**Issue by tuanducdesign** [shuding/nextra#1145]
Error: Image Optimization using Next.js' default loader is not compatible with `next export`.
  Possible solutions:
    - Use `next start` to run a server, which includes the Image Optimization API.
    - Configure `images.unoptimized = true` in `next.config.js` to disable the Image Optimization API.
  Read more: https://nextjs.org/docs/messages/export-image-api

Currently I am using nextra on my own server

**Comment by B2o5T** [comment]
The fix is in the error message -  Configure images.unoptimized = true in next.config.js to disable the Image Optimization API.

**Comment by tuanducdesign** [comment]
```js
images: {
  unoptimized: true
}
```

Not working :(

**Comment by mkrtchian** [comment]
I have a working example [here](https://github.com/mkrtchian/reading-notes), it is exported and hosted on Github Pages in a fully static way.

To make it work you need to pass the Next.js options (like `images.optimized`) to the final exported object, instead of passing it among Nextra's options when calling  `require("nextra")()`.

```javascript
// next.config.js

const withNextra = require("nextra")({
  theme: "nextra-theme-docs",
  themeConfig: "./theme.config.tsx",
});

const nextConfig = {
  images: {
    unoptimized: true,
  }
};

module.exports = {
  ...withNextra(),
  ...nextConfig,
};
```

(Taking into account all Next.js config options in Nextra's config directly may be something we would like to be supported by the way)

**Comment by tuanducdesign** [comment]
Thanks
