### ISSUE TITLE
Not adding styles to MDX files when inside of a Turborepo

### ISSUE THREAD

**Issue by vestimir** [shuding/nextra#1158]
I've added Nextra to a project with Turborepo. It runs OK, but markdown in the .mdx files is not rendering with any styles:

<img width="363" alt="Screenshot 2023-01-01 at 11 05 01" src="https://user-images.githubusercontent.com/356117/210167133-6591073a-f8aa-42c8-b4dc-1aea0b748f96.png">

It's not attaching any tailwind classes to the content from `pages/index.mdx`. 

These are my dependencies:

```json
"dependencies": {
    "next": "^13.1.1",
    "nextra": "^2.0.2",
    "nextra-theme-docs": "^2.0.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
}
```

Any clues on how to fix this?

**Comment by C-EO** [comment]
I'm having the same problem

@shuding is there a fix?

**Comment by promer94** [comment]
Thanks for reporting this !

Could you provider a reproduction here or share us more infomaiton about your turborepo ?

I try to reproduce the problem here https://github.com/promer94/turbo-nextra. But it works fine.  

It would be really helpful if we could have more information here.

**Comment by vestimir** [comment]
Here's an example repo:
https://github.com/vestimir/nextra-example-monorepo

**Comment by promer94** [comment]
The problem here is that there are two different version of `@mdx-js/react` was installed in your monorepo and got hoisted.

* Storybook use @mdx-js/react 1.x
* Nextra use @mdx-js/react 2.x

<img width="520" alt="CleanShot 2023-01-02 at 02 49 22@2x" src="https://user-images.githubusercontent.com/15878786/210181654-684c4a4b-a675-4079-89b9-21d59e8915d6.png">

you need to add a special [nohoist config](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/) in your `docs`'s  `package.json`. So that nextra will be able use the correct mdx version.

```
{
   "workspaces": {
    "nohoist": [
      "nextra",
      "nextra-theme-docs"
    ]
  },
}
```

**Comment by vestimir** [comment]
@promer94 thank you very much! All works great now.
