### ISSUE TITLE
A strange problem with folders count in /pages (2.0.2)

### ISSUE THREAD

**Issue by alex-flea** [shuding/nextra#1162]
`yarn dev` and `yarn build` stucks when more than 19 folders are present in '/pages' (version 2.0.2).
Version 2.0.1 does not experience such problem.

**Comment by promer94** [comment]
This problem was introduced in #1127

In #1127, `p-limit` was added to limit the concurrency of `collectFiles`. However, `collectFiles` is recursive function. It will create tasks depends on each others.

if `pages` has 20 folders, `collecctFiles` will add 20 tasks to `p-limit` queue. 

During task's excution, new sub-tasks will be added to the queue and it has to wait the previous tasks to finish.
But tasks also need to wait sub-tasks to finish. DeadLock happens 🫥
