### ISSUE TITLE
Cache `getDynamicMeta`

### ISSUE THREAD

**Issue by shuding** [shuding/nextra#1316]
CC @B2o5T, for production builds the `getDynamicMeta` function will be executed for every route, is there any chance to cache it to reduce build time and memory usage?

**Comment by B2o5T** [comment]
done https://github.com/shuding/nextra/pull/1294

https://github.com/shuding/nextra/blob/b1f28128902dc2b5b1145cedec3ab1676c2696ac/packages/nextra/src/page-map.ts#L51-L54

https://github.com/shuding/nextra/blob/b1f28128902dc2b5b1145cedec3ab1676c2696ac/packages/nextra/src/page-map.ts#L69-L74

also, I cached the result of `globalThis.__nextra_resolvePageMap` because received the rate limit from the gists github

https://github.com/shuding/nextra/blob/fff9f6b4937f926606083e6205d5d752a407a0ec/packages/nextra/src/setup-page.ts#L92

https://github.com/shuding/nextra/blob/fff9f6b4937f926606083e6205d5d752a407a0ec/packages/nextra/src/setup-page.ts#L114-L117

https://github.com/shuding/nextra/blob/fff9f6b4937f926606083e6205d5d752a407a0ec/packages/nextra/src/setup-page.ts#L136
