### ISSUE TITLE
Enabling i18n breaks access to the static files (and also indexes in subfolders)

### ISSUE THREAD

**Issue by alex-flea** [shuding/nextra#1354]
After enabling i18n and configuring it according to https://nextra.site/docs/guide/i18n static files in `/public` are no longer servered (such as `sitemap.xml`). The problems seems to be in the middleware (but it's the same as described in the docs):

```
export { locales as middleware } from 'nextra/locales'
```

The problem described in the issue #1263 (https://github.com/shuding/nextra/issues/1263) also seems to be related to this one (due to middleware?).

**Comment by B2o5T** [comment]
`sitemap.xml` would be fixed, which static files are also not served properly? I'm closing this issue since it's duplicate #1263

**Comment by B2o5T** [comment]
all files with `.xml` extension will be served properly in next release

**Comment by SeeSharpDeveloper** [comment]
This issue is still present with other files like *.pdf *.zip or other non-standard-web documents. 
without i18n these files are accessable i.e for download. After enabling i18n the files are not found (404).

for download i was able to do a magic trick with changing the extension to one of the allowed ones (txt, xml, png) and switching the filename on download:

`<a href="/static/files/sample2.zip.txt" download="sample2.zip">download zip _ </a>`

**Comment by SeeSharpDeveloper** [comment]
If you use middleware, you can select which folders from the public folder should be ignored by i18n.

middleware.ts:
```ts
import { NextRequest } from 'next/server';
import { locales } from 'nextra/locales';

export async function middleware(req: NextRequest) {
  const pathIsStaticFile = req.nextUrl.pathname.startsWith('/static/');
  if (pathIsStaticFile) {
    return;
  }
  return locales(req);
}
```
