### ISSUE TITLE
mermaid in nextra

### ISSUE THREAD

**Issue by crguezl** [shuding/nextra#1373]
Can I use mermaid with nextra?

Something like in [docusaurus](https://docusaurus.io/docs/markdown-features/diagrams#configuration)?

**Comment by B2o5T** [comment]
Will be available soon

**Comment by sortegamartin** [comment]
In the meantime, would there be any workaround to be able to use it?

**Comment by shuding** [comment]
Any Mermaid lib for React or MDX can be used in Nextra.

**Comment by LuciferUchiha** [comment]
You could also just use a remark plugin such as this one: https://github.com/temando/remark-mermaid

I did the same for plantUML: https://github.com/akebifiky/remark-simple-plantuml

And then just add it in the next config: https://github.com/LuciferUchiha/nextra-garden/blob/main/next.config.mjs#L14

**Comment by mariansimecek** [comment]
Any updates? It would be nice to have a working mermaid out of the box. I was not able to configure it with any available remark plugins. Except for https://github.com/remcohaszing/remark-mermaidjs but I don´t like Puppeteer dependency :(

**Comment by Songkeys** [comment]
You can create one on https://mermaid.live/ and export it with an svg uri. then embed it in image markdown.

**Comment by TomasHubelbauer** [comment]
@Songkeys that is a good solution for some cases but for many people it won't work because we are hoping to have the source code of the diagram to be the source of the truth and have the rendering be a function of that source code. That way the two are always in sync. When relying on a manual copy-pasting process either the original source code is lost (if you just paste in the SVG) or you paste both into the document but then there is a risk of the two going out of sync if you ever forget the manual step. An ideal solution would be for Nextra to render Mermaid automatically.

**Comment by Songkeys** [comment]
@TomasHubelbauer 

> When relying on manual copy-pasting, there is a risk of losing the original source code (if you just paste in the SVG).

Fortunately, <https://mermaid.live> has an action section that allows you to copy and paste the markdown URL for SVG or PNG. For example, the SVG markdown looks like this:

`[![](https://mermaid.ink/img/pako:eNpVjstqw0AMRX9FaNVC_ANeFBq7zSbQQrPzZCFsOTMk80CWCcH2v3ccb1qtxD3nCk3Yxo6xxP4W760lUTjVJkCe96ay4gb1NJyhKN7mAyv4GPgxw_7lEGGwMSUXLq-bv18lqKbjqjGodeG6bKh69r8Cz1A3R0oa0_kvOd3jDB-N-7b5_H9ihXPrs-mp7KloSaAieSq4Q8_iyXX5_WlNDKplzwbLvHYkV4MmLNmjUePPI7RYqoy8wzF1pFw7ugj5LVx-AfLqVWg?type=png)](https://mermaid.live/edit#pako:eNpVjstqw0AMRX9FaNVC_ANeFBq7zSbQQrPzZCFsOTMk80CWCcH2v3ccb1qtxD3nCk3Yxo6xxP4W760lUTjVJkCe96ay4gb1NJyhKN7mAyv4GPgxw_7lEGGwMSUXLq-bv18lqKbjqjGodeG6bKh69r8Cz1A3R0oa0_kvOd3jDB-N-7b5_H9ihXPrs-mp7KloSaAieSq4Q8_iyXX5_WlNDKplzwbLvHYkV4MmLNmjUePPI7RYqoy8wzF1pFw7ugj5LVx-AfLqVWg)`

The image also has an edit link attached, so you can click it and make changes if needed. After editing, you can copy and paste the markdown again.

If you lose the <https://mermaid.live> edit link, don't worry - you can simply change `mermaid.ink/img/` to `mermaid.live/edit` to edit it.

I'm providing this solution because I know how difficult it can be to find a library and struggle to integrate it when the framework doesn't support something natively. Additionally, you risk migrating the document to other frameworks and losing the rendering again. So, this "external support" solution is the best option for me. It makes my life easier.

However, it's important to keep in mind that the website could potentially go down someday. To avoid the risk of losing your work, you might consider self-hosting the solution (it's open-source), or, yes, finding a library to render it.

**Comment by TomasHubelbauer** [comment]
I strongly believe this should be a built-in feature of Nextra seeing how vastly supported Mermaid is (e.g. GitHub supports it natively in Markdown), but in the meanwhile before this hopefully ships out of the box, check out @mariansimecek's package here:

https://github.com/mariansimecek/remark-mermaid-nextra

I've tested it and it works great.
