### ISSUE TITLE
How to use Tailwind CSS?

### ISSUE THREAD

**Issue by jvzaniolo** [shuding/nextra#1576]
I installed Tailwind CSS as a PostCSS plugin in Nextra, but when I try to import the `.css` file inside `pages/_app.{mdx|tsx}`, I get the following error:

```
error - ./pages/_app.mdx:7:0
Module not found: Can't resolve '../styles/globals.css'
   5 | /*@jsxRuntime automatic @jsxImportSource react*/
   6 | import $NextImageNextra from "next/image";
>  7 | import '../styles/globals.css';
   8 | const MDXLayout = function App({Component, pageProps}) {
   9 |   return <Component {...pageProps} />;
  10 | };

https://nextjs.org/docs/messages/module-not-found
```

```
error - ./pages/_app.tsx:1:0
Module not found: Can't resolve '../styles/globals.css'
> 1 | import '../styles/globals.css';
  2 |
  3 | export default function App({ Component, pageProps }) {
  4 |   return <Component {...pageProps} />;

https://nextjs.org/docs/messages/module-not-found
```

And if I try to import it in any other file:

```
./styles/global.css
Global CSS cannot be imported from files other than your Custom <App>. Due to the Global nature of stylesheets and to avoid conflicts, Please move all first-party global CSS imports to pages/_app.js. Or convert the import to Component-Level CSS (CSS Modules).
Read more: https://nextjs.org/docs/messages/css-global
Location: theme.config.tsx
```

**Comment by B2o5T** [comment]
take a look of working example https://github.com/shuding/nextra/blob/main/examples/swr-site/tailwind.config.js

**Comment by cglacet** [comment]
The "working exemple" provided by @B2o5T doesn't work anymore (at least not with the **docs** theme). Because they removed the prefix from the dark selector. Today, dark selectors most likely look like this `"dark:nx-..."`. Notice there is a prefix on the class name, but not on the `dark` selector.

## Solution

In addition to the steps described in tailwind's documentation [Install Tailwind CSS with Next.js](https://tailwindcss.com/docs/guides/nextjs). You will have to configure the `dark` theme selector to work properly. Depending on the theme you chose it may vary but it should look something like (`/tailwind.config.js`):

```ts
/** @type {import('tailwindcss').Config} */
module.exports = {
  prefix: "nx-",
  darkMode: ["class", 'html[class~="dark"]'],
  content: [
    "./components/**/*.{ts,tsx}",
    "./pages/**/*.{md,mdx}",
    "./theme.config.tsx",
  ],
};
```

Don't remove the `nx-` prefix (as it would create duplicated CSS classes). 

Instead have a look at your theme's tailwind config, for exemple in the **docs** theme the config is [here](https://github.com/shuding/nextra/blob/main/packages/nextra-theme-docs/tailwind.config.js), and look at how the dark theme selector is defined, copy it to your config.

If needed, here is a more [detailed explanation](https://github.com/shuding/nextra/issues/1495#issuecomment-1510300602).

**Comment by cglacet** [comment]
Using the above mentioned configuration there is still an issue but I think the problem comes from the docs theme. If I use the `nx-` prefix and that I use `nx-hidden` anywhere in my own files it breaks the docs theme (search bar/toc/ and some other components not visible anymore).
