### ISSUE TITLE
Lighthouse warning: Links are not crawlable

### ISSUE THREAD

**Issue by transitive-bullshit** [shuding/nextra#1635]
Using the `nextra` and `nextra-theme-docs` defaults, Lighthouse complains about:

<img width="863" alt="CleanShot 2023-03-13 at 12 43 54@2x" src="https://user-images.githubusercontent.com/552829/224784698-07b2e428-5255-4447-91bf-04cdca29ee0a.png">

- [Lighthouse link](https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fsklearn.vercel.app%2F&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext)
- [site link](https://sklearn.vercel.app/)

This looks to be related to internal `#` links, but I'm not 100% sure.

Cheers 🙏

**Comment by B2o5T** [comment]
Nice catch, this happens due folders
<img width="261" alt="image" src="https://user-images.githubusercontent.com/7361780/224848328-37323a3f-3745-428e-9665-b5124e6c5e65.png">

because they have empty `href`
<img width="409" alt="image" src="https://user-images.githubusercontent.com/7361780/224848445-134053ee-ef92-4007-9790-cf5bb6b26d12.png">

we can improve it by using `<button />` instead `<a />` for such as folders

**Comment by ImBIOS** [comment]
![Screenshot 2023-03-14 at 07 54 29](https://user-images.githubusercontent.com/41441643/224864714-91bade73-9114-4793-a45c-7f34e333bf3e.jpg)

It's already solved (?) If so, @transitive-bullshit this should be marked as closed.

**Comment by abhaytalreja** [comment]
Any ETA / schedule on this item? - This impacts the SEO score of the entire website and Google punches the site lower in searches.
