### ISSUE TITLE
Is there any way to parse file with chinese content directly without _meta.json?

### ISSUE THREAD

**Issue by sailist** [shuding/nextra#1739]
For example, `pages/中文.mdx` will raise 404 error, how to directly support UTF-8 paths dynamically without _meta.json?  ​​​I have read the content of https://github.com/shuding/nextra/issues/97, but it didn't help.

**Comment by oeyoews** [comment]
I think this is a urI encoding problem. For example, file names like `Chinese Test.mdx` will also encounter 404 problems, because the special characters of this file name are encoded by the browser, which is no longer consistent with the file name. Read I can’t get the corresponding file, I think just adding a decodeURI(slug) can solve this problem, because I just saw nextra today, so I’m not very familiar with the relevant code

**Comment by B2o5T** [comment]
No way https://github.com/shuding/nextra/issues/983#issuecomment-1331425509
