### ISSUE TITLE
A directory instead  of an extension at I18N.

### ISSUE THREAD

**Issue by jakekwak** [shuding/nextra#176]
When I need to translate, it seems more convenient to make a translation file after copying it to a directory, rather than changing the extension of all files.

```
pages
  meta.en_US.json
  meta.ko_KR.json
```

```
pages/
  en_US/
    meta.json
  ko_KR
    meta.json
  zh_CN
    meta.json
```

**Comment by niikeec** [comment]
@B2o5T Would the current format still be supported? I'm interested in implementing this.

**Comment by B2o5T** [comment]
closed by https://github.com/shuding/nextra/pull/2250

https://github.com/shuding/nextra/releases/tag/nextra%403.0.0-alpha.0

**Comment by RiverTwilight** [comment]
Hi @dimaMachina @shuding 

I need to use different domains for region-specific content and localization - for example, `example.com` for global users and `example.com.cn` for users in China. This allows redirecting visitors to appropriate regional domains (similar to how Apple uses apple.com and apple.com.cn).

Nextra 2 works well with this approach since I can dynamically modify the `locale` configuration in next.config.js for different deployment targets:

```js
import defaultConfig from "./default-config.mjs";
import nextra from "nextra";
const withNextra = nextra({
    theme: "./theme.tsx",
});

const targetRegion = process.env.TARGET_REGION;
let config;

if (targetRegion === "china") {
    config = {
        ...defaultConfig,
        i18n: {
            locales: ["zh-CN"],
            defaultLocale: "zh-CN",
        },
    };
} else if (targetRegion === "global") {
    config = {
        ...defaultConfig,
        i18n: {
            locales: ["en-US", "zh-CN"],
            defaultLocale: "en-US",
        },
    };
} else {
    config = defaultConfig;
}

export default withNextra(config);
```

However, this functionality isn't available in V3 or V4. The current implementation only supports path-based localization (like "/en" or "/zh"). I do not want an URL like "example.com.cn/zh" or "example.com/en". This is particularly important since I'm not just translating content - I need to adjust content based on local laws and regulations.

While the current implementation works, I would prefer to maintain the domain-based i18n approach. If there are no plans to restore this functionality, **I'm interested in contributing to Nextra 2 to help maintain it and potentially backport new features from Nextra 4, such as MDX 4 support.**

**Comment by dimaMachina** [comment]
Please create a new issue, there will be no updates for Nextra 2 and 3
