### ISSUE TITLE
png images problem. Feedback for “Next.js Image”

### ISSUE THREAD

**Issue by washirving** [shuding/nextra#1779]
nextra ruining png images. it's adding blurry background to them.

That's how images looks like on page:
![ss+(2023-04-20+at+03 12 39)](https://user-images.githubusercontent.com/2457006/233362434-63f01884-e0ce-40c1-85e5-6c04bcd1c4da.jpg)

but should be:
![ss+(2023-04-20+at+03 15 01)](https://user-images.githubusercontent.com/2457006/233362843-006144c0-fb06-4bcf-b872-561b24b8f4dd.png)

```
module.exports = {
  images: {
    unoptimized: true,
  },
}
```
as it says here https://nextjs.org/docs/api-reference/next/image#unoptimized not working

how to disable adding 
style="color:transparent;background-size:cover;background-position:50% 50%;background-repeat:no-repeat;background-image:url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http%3A//www.w3.org/2000/svg' viewBox='0 0 8 6'%3E%3Cfilter id='b' color-interpolation-filters='sRGB'%3E%3CfeGaussianBlur stdDeviation='1'/%3E%3C/filter%3E%3Cimage preserveAspectRatio='none' filter='url(%23b)' x='0' y='0' height='100%25' width='100%25' href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAMAAADJ2y/JAAAAKlBMVEUAAAAAAAAAAABMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADZ5hg9AAAADnRSTlO8oHUAqiJDitMEKxQMVSTOjQAAAAAJcEhZcwAACxMAAAsTAQCanBgAAAAvSURBVAiZJcG3AcAwEAOxI/VByfuv60IA6jwrvyICdWAcPTGgCZZFVebZdzOe9QMWpgDVIhmPSgAAAABJRU5ErkJggg=='/%3E%3C/svg%3E")" to them?

**Comment by abhaytalreja** [comment]
@washirving I am using transparent images on my site and they come out okay with the default setting. Can you share the component where the images are displayed? (JSX/TSx/MDX) code?

You can take a look at my website - [Website for learning Agile](https://teachingagile.com 'Teaching Agile')

**Comment by washirving** [comment]
> @washirving I am using transparent images on my site and they come out okay with the default setting. Can you share the component where the images are displayed? (JSX/TSx/MDX) code?
> 
> You can take a look at my website - [Website for learning Agile](https://teachingagile.com)

every single mdx page with any png image gives same result even if content is just

![](/img.png)

png image is clean and located in /public folder.  
I cant figure what exactly adding that strange unclosed parameter to style tag « background-image:url("data:image/svg+xml; »

**Comment by washirving** [comment]
> You can take a look at my website - [Website for learning Agile](https://teachingagile.com)

what a wonderfull «About Abhay Talreja» block with social links! how did you do this?

**Comment by washirving** [comment]
Yes! it happtning again. I made brand new project on vercel from template and added just single png image with tranparency and same result. tested on win10, mac and phone. no any other changes on pero.
https://newdocks.vercel.app/

**Comment by abhaytalreja** [comment]
Okay, i figured out the problem. The about section for me is the `next/Image` so it didn't cause an issue. However, for all the `.mdx` image files, there is a style that is getting applied to all the images.

`color: transparent; background-size: cover; background-position: 50% 50%; background-repeat: no-repeat; background-image: url("/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fabhay-talreja-agile-coach.b551c86c.png&w=8&q=70");`

The problem is the quality of `70` getting applied to the images. I am not sure where this code sits. If it is coming from `Nextra` or not. If you remove this style, it will work.

A Simple fix you can do in the markdown is below. Just make the quality parameter as `100` and it will just work fine.

`
![](/img.png?q=100)
`

I hope it helps. 

Thank you for showing love to my attempt to teaching [Agile principles](https://teachingagile.com/ 'Teaching Agile')

**Comment by B2o5T** [comment]
Please report in Next.js repo
