### ISSUE TITLE
HTML Size is large

### ISSUE THREAD

**Issue by abhaytalreja** [shuding/nextra#1796]
Hi There,

I am trying to craete the app with many pages. Because we have the left navigation, as well as on page on the right sidebar. There are many html elements created.

Is there a way, we can add an option to load child links on the left navigation only when it is expanded? That will surely reduce the HTML size the search console is finding as an issue.

![Screenshot 2023-04-25 at 12 01 15 PM](https://user-images.githubusercontent.com/1915902/234335699-ed448031-ef00-4544-9516-735d16e7807c.png)

**Comment by abhaytalreja** [comment]
Thank you @B2o5T - I have deployed it, will validate in the search console. Appreciate it.

**Comment by dacevedo12** [comment]
I'm experiencing the same and this time the _app.mdx trick does not apply.

This issue is about the hidden mobile sidebar https://github.com/shuding/nextra/blob/fb43fb6dfacf2d664dee28c3f1b768c0df0a123c/packages/nextra-theme-docs/src/components/sidebar.tsx#L453

In my case with 3000+ pages, each index.html is 2.3MB. This means a slow build process of 1 hour and 4GB in total assets size when deploying

**Comment by B2o5T** [comment]
@dacevedo12 Yeah, I was thinking of hiding mobile sidebar too

**Comment by dacevedo12** [comment]
For reference, docusaurus handles it by only generating the collapsible sidebar items of the current page, not the root paths. i.e

<img width="351" alt="image" src="https://github.com/shuding/nextra/assets/29694570/1f3e4c16-0c47-48ab-a53d-2d1dfa6dd896">

After clicking back to main menu, it shows the root paths, which are non collapsible

<img width="321" alt="image" src="https://github.com/shuding/nextra/assets/29694570/39925bb3-f306-44a9-917a-16c4bd74f43c">
