### ISSUE TITLE
How to use external dynamic libraries in an MDX page with Nextra and Next?

### ISSUE THREAD

**Issue by LunaticMuch** [shuding/nextra#1979]
I am playing a bit with Nextra and MDX.

One thing I would like to include is a voyager or a graphiql component. More or less it is like in [CodeGenerator](https://the-guild.dev/graphql/codegen) or in [Mesh](https://the-guild.dev/graphql/mesh/examples) examples from The Guild.

However, I get an amount of errors. Concentrating myself with Voyager, I found that [this implementation](https://github.com/LunaticMuch/vigilant-octo-invention/blob/main/components/voyager.tsx) I made does make the [MDX file](https://github.com/LunaticMuch/vigilant-octo-invention/blob/main/pages/voyager.mdx) to fail with `Error [ReferenceError]: self is not defined`.

I tried some other options, including a dynamic call as I found in Mesh, but I can't get past the issue.
Likewise, the GraphiQL example does not work. This one complains with fetcher issues 😕 

I am confused how it should be taken care. As MDX is like JSX, it should be quite easy, but somehow my code has something wrong (or the website generation is possible a problem as it can be statically generated).

Has anybody making a similar usage and able to provide a hint?

**Comment by B2o5T** [comment]
I am also confused that

1. you provide `tsx` extension
https://github.com/LunaticMuch/vigilant-octo-invention/blob/1dc460b9ce1ea2caae6f470b561ecb3ab05572c2/pages/voyager.mdx?plain=1#L6
2. you `export default App` but import named `{ App }`
https://github.com/LunaticMuch/vigilant-octo-invention/blob/1dc460b9ce1ea2caae6f470b561ecb3ab05572c2/pages/voyager.mdx?plain=1#L6
3. you use `fetch` without `useEffect` https://github.com/LunaticMuch/vigilant-octo-invention/blob/1dc460b9ce1ea2caae6f470b561ecb3ab05572c2/components/voyager.tsx#L5

Anyway, this is not the right place of asking general questions.

Feel free to integrate Voyager in the regular next.js app (or ask the maintainer of the library how to integrate it in Next.js) and after you could integrate it in Nextra too.

Also, I guess you will need `next/dynamic` since this component doesn't work with SSR.
