### ISSUE TITLE
how to deploy this repo as it is ?

### ISSUE THREAD

**Issue by abhinavpatel0** [shuding/nextra#2001]
thank you so much for this awesome project, i am trying to deploy this exact website to vercel but it shown a error  "there is no public directory available" , i want to deploy this repo because i want play its code and learn and wants to see and make some fundamental changes on how it works , please help me what should i do so that i can deploy this repo on vercel

**Comment by hugihlynsson** [comment]
@abhinavpatel0 I believe the website lives in the `/docs` folder. You'd either have to deploy that folder to Vercel or set the _Root Directory_ settings in your Vercel project to `docs`. Hope this helps!

**Comment by abhinavpatel0** [comment]
> @abhinavpatel0 I believe the website lives in the `/docs` folder. You'd either have to deploy that folder to Vercel or set the _Root Directory_ settings in your Vercel project to `docs`. Hope this helps!

i tried this alreadt but sadly this doesnt work, thanks

**Comment by hugihlynsson** [comment]
I just tried this and here are more detailed instructions:

1. Get the code by cloning this repo or downloading the zip file
2. Open the `/docs` folder
3. In `package.json` replace the two instances of `workspace:*` with the latest Nextra version (currently `^2.8.0`) so that lines 16 and 17 look something like this:
    ```
    "nextra": "^2.8.0",
    "nextra-theme-docs": "^2.8.0",
    ```

4. Deploy to Vercel: `vercel` or `npx vercel` 

Here is my build: https://nextra-hzqzaolzi-hugihlynsson.vercel.app/

**Comment by abhinavpatel0** [comment]
thank you so much for help , but i want to know if i can deploy it with the workspace because i want to change some things in package itself and so if its possible to include my changed package in production without publishing my package on npm that would be great

**Comment by hugihlynsson** [comment]
Ahh yes of course! Turns out, it's just a matter of a couple of Vercel settings. As I mentioned earlier you need to set the root directory to `docs`, leave the "Include source files outside of the Root Directory in the Build Step" box checked and then set the Framework preset to "Next.js", like this:

<img width="933" alt="Screenshot 2023-06-29 at 10 45 47" src="https://github.com/shuding/nextra/assets/4923531/961d25cb-d851-4bce-b715-91da19fac007">

With these settings the project should build and deploy out of the box based on your local Nextra code.
