### ISSUE TITLE
Search memory leak

### ISSUE THREAD

**Issue by lokhmakov** [shuding/nextra#2150]
On nextra based sites you can write in search > space space and any letter and fast memory leak happens.

Affected only production builds. (Safari, Chrome based browsers, Mac)

https://github.com/shuding/nextra/assets/94939/63df3d3e-c2d7-40ad-b2fc-8a84d0d1ff67

**Comment by guilherssousa** [comment]
Just some additional info about the problem:
1. Any input (as long its not empty) followed by two spaces and a single character will leak
2. You can also reproduce the same behaviour on development environment by building the project, and then running in development mode (because it maps all available contents in `.next/static/chunks/pages`)

**Comment by B2o5T** [comment]
https://github.com/shuding/nextra/blob/fix-memory-leak/packages/nextra-theme-docs/src/components/highlight-matches.tsx#L27-L29
