### ISSUE TITLE
Feedback for “Nextra Docs Theme”

### ISSUE THREAD

**Issue by iamgideonai** [shuding/nextra#2445]
Hi, 

Firstly I loved Nextra Documentation theme and its being currently implemented in our company products documentation sites. 

Also would like to know, whether is it possible to add Authentication to the documentation theme as we want to restrict the access to authorized  users only for couple of documentation sites. Have tried implementing with AWS Cognito but having tough time making it work as i am new to next js. 

If possible, Request you to provide few instructions in applying any of the authentication (NextAuth / Clerk / Cognito / Auth0 etc.,) to doc theme.  Thank You!

**Comment by dyoungwd2** [comment]
using magic.link works - follow the guide to set up a magic.link app for next.js then install the theme following nextra docs guide.  Because you will want the mdx pages behind authentication you will need to set a custom component an import that into the mdx files so only authenticated users  can gain access. It is possible to do

**Comment by dimaMachina** [comment]
https://github.com/shuding/nextra/issues/1121#issuecomment-1374958546
