### ISSUE TITLE
Hydration errors caused by links with URLs as text

### ISSUE THREAD

**Issue by ankrgyl** [shuding/nextra#2663]
If you add a URL as a link, e.g. 

```
# About

This is the about page! This page is shown on the navbar.

<a href="https://www.google.com">https://www.google.com</a>
```

(modified from https://github.com/shuding/nextra-docs-template/blob/main/pages/about.mdx)

You get a hydration error because the link gets pre-processed into a nested `<a>` tag.

<img width="1097" alt="Screenshot 2024-01-28 at 5 07 25 PM" src="https://github.com/shuding/nextra/assets/565363/80dc6d90-f36a-4e44-9f45-46bc92327452">

Note that I ran `pnpm install` and then `pnpm update -r` to repro (it doesn't repro with just `pnpm install`).

**Comment by dimaMachina** [comment]
text which starts with `http://`, `https://` and `www` you don't need to wrap with markdown links, because they will be anyway processed by `remark-gfm`

If you wrap such as text, this results in invalid HTML since you can't have `<a />` inside `<a />`

try it https://mdxjs.com/playground/
<img width="1586" alt="image" src="https://github.com/shuding/nextra/assets/7361780/95d063f8-ed7a-420c-8818-2525b498d218">

**Comment by ankrgyl** [comment]
Yeah I'm aware that it extra wraps it, but sometimes I'm working with markdown that's generated from other systems, and it contains `<a href="...">https://...</a>`, which I now have to manually strip.

Agree that it's not necessary to write markdown this way, but it'd be nice if it didn't throw an error.

**Comment by dimaMachina** [comment]
as a workaround, you can write `remark` or `rehype` plugin which modifies AST and removes nested `<a>` and provide it to nextra config similar to https://nextra.site/docs/guide/advanced/table#setup
