### ISSUE TITLE
Feedback for “CSM.AI Documentation”

### ISSUE THREAD

**Issue by shafiqa15** [shuding/nextra#2876]
Hi I'm Shafiqa ,I'm a 4th year undergraduate student studying on Palestine at An-najah National University 
I want to use ur website api in my react app for my graduation project , I tried so hard to connect it but no solutions
can u help me to connect ur api in my project ?

**Comment by Fun117** [comment]
Hello, shafiqa15.

This issue appears unrelated to Nextra and seems more like a request for assistance rather than a problem. If you need help with CSM.AI's API, please create an issue in a directly related location. You'll likely find support in [CSM.AI's documentation](https://docs.csm.ai/), support page, or associated [community](https://discord.gg/csmai) forums.

**Comment by dimaMachina** [comment]
closing since unrelated to Nextra
