### ISSUE TITLE
How to use in single website with both landing page and /docs route.?

### ISSUE THREAD

**Issue by softmarshmallow** [shuding/nextra#291]
I have this site grida.co - https://github.com/gridaco/grida.co
Which has both landing page and docs site (currently not using nextra)

And I'm wondering if i can spcecify nextra to only interpret specific directory - /docs and convert them to a docs site. not all of the entire repository.

Thanks!

**Comment by PabloLION** [comment]
I want this too. Will this be available in nextra v2.0?

**Comment by PabloLION** [comment]
I tested some work-arounds in NextJS Docs. 

1. Add a `/pages/docs` folder
  Just add this folder and Nextra will handle all `.mdx` file. The problem with this method is that all pages will show always show a top level "docs" folder. 
2. With basePath
  Here in https://nextjs.org/docs/migrating/incremental-adoption, there's an option to host a NextJS as subpath. Notice that you need to pass the `nextConfig` into `withNextra`. Problem here is I don't know and I didn't test if a rewrite is needed.

**Comment by PabloLION** [comment]
The repo I used to test is here https://github.com/PabloLION/test-nextra

**Comment by bube5h** [comment]
> The problem with this method is that all pages will show always show a top level "docs" folder.

Atleast, we can move "docs" from sidebar to NavBar by creating `_meta.json` outside "docs" folder with contents
```
{
    "docs": {
      "title": "Docs",
      "type": "page"
    }
}
```

Before:
<img width="1451" alt="image" src="https://github.com/shuding/nextra/assets/34552173/5c345aa2-e4eb-4240-8b8d-37cd8e75cb62">

After:
<img width="1451" alt="image" src="https://github.com/shuding/nextra/assets/34552173/8479386f-02c3-463e-aff7-10c543341393">

Ref: https://nextra.site/docs/docs-theme/page-configuration#navbar-items

**Comment by karlimbar** [comment]
@bube5h 's workaround works but it's sort of tricking Nextra. For example, you still see `Docs > Index` on the page which is irrelevant for that page as it's the entry point for the user and also when you click to logo, it redirects to the root domain not `/docs` page.

I think an option like `basePath` in the theme config would be great to tell Nextra just treat that given folder (like `pages/docs`) as its root path. If needed, `baseUrl` could also work to tell it that it's being served under `/docs` path.

Also I'd want to add that this style of deployment, eg subpath of a landing page, is quite common for SEO purposes since you get quite a bit of docs content linked from other websites.

**Comment by karlbaumg** [comment]
I'm trying this with Nextra v4. One thing that's problematic is that there are places Nextra assumes ownership of the root CSS styles, like `<Head>` component has CSS to set `html` and `::selection`. Not sure how to limit them without forking.

**Comment by huykon** [comment]
then how can we do?
