### ISSUE TITLE
[v3] Broken MDX import

### ISSUE THREAD

**Issue by andrii-bodnar** [shuding/nextra#2951]
I have some common parts in my documentation that I would like to import as separate files. It's possible according to [this](https://the-guild.dev/blog/nextra-2#markdown-import).

But when I import the mdx file into another mdx, the imported content doesn't show up, just headings get mixed up with the original page heading. 

For example, I have the following `test.mdx`:

```mdx
## Common content

common content

### Subsection 1

subsection 1 content
```

And I import it into the [Introduction](https://github.com/shuding/nextra/blob/v3/docs/pages/docs/index.mdx) page:

```mdx
import test from './test.mdx'

# Introduction

**Nextra** is a framework on top of Next.js, that lets you build content focused
websites. It has all the great features from Next.js, plus extra power to create
Markdown-based content with ease.

<test />

test

## Quick Start

import { Cards } from 'nextra/components'

To start using Nextra, you need to select a theme first:

...
```

**Result:**

![Screenshot 2024-06-27 at 17 18 11](https://github.com/shuding/nextra/assets/29282228/9ead525f-6832-42f9-8fc2-934aeff89ae3)

**Comment by 87xie** [comment]
I referred to the MDX's [using MDX guidelines](https://github.com/mdx-js/mdx/blob/07d5e2fcf304ee94dae397c7ba0b3e6776f33c34/docs/docs/using-mdx.mdx?plain=1#L326-L339):

>‡ The rules for whether a name in JSX (so x in <x>) is a literal tag name (like h1) or not (like Component) are as follows:
>
> - If there’s a dot, it’s a member expression (<a.b> → h(a.b)), which means a reference to the key b taken from object a.
> - Otherwise, if the name is not a valid JS identifier, it’s a literal (<a-b> → h('a-b')).
> - Otherwise, if it starts with a lowercase, it’s a literal (<a> → h('a')).
> - Otherwise, it’s a reference (<A> → h(A)).

My guess is as follows:

- In the above example, `test` starts with a lowercase letter, so MDX treats it as an HTML tag and compiles it to `_jsx('test')` instead of `_jsx(test)`.
- The headings in the TOC are parsed by Nextra's `remark-headings` plugin, which determines the headings based on the ESM exports.

I think a simple solution would be to rename `test` to UpperCamelCase so that MDX can correctly parse it as a component:

```mdx
import Test from './test.mdx'

<Test />
```
