### ISSUE TITLE
Docs on how to customize/create your own themes

### ISSUE THREAD

**Issue by shuding** [shuding/nextra#41]
https://twitter.com/benoror/status/1336354020357705734

**Comment by YikSanChan** [comment]
related to https://github.com/shuding/nextra/issues/31

**Comment by YikSanChan** [comment]
Just curious, is `theme.config.js` the place where all the customization goes?

**Comment by dirtybirdnj** [comment]
Hi I discovered nextra over the past weekend and I really like it. I've started working with it and customizing the header is a HUGE headache.

That I am using the blog theme vs the docs theme seems to be the root issue. It's very hard to understand how I can either customize the blog theme, or fork it and change it to my needs.

Please provide more info on this, nextra is fantastic and this is IMO a real missing piece. 

It's especially confusing because the footer is very customizable, but the header is not? This combined with the "coming soon" docs and finding outstanding issues that are 2 years old is :(

I hope my post here bumps the interest in the blog docs. If there's a way I can help please let me know.

**Comment by shuding** [comment]
We've revamped the API for custom themes and added docs for that recently, take a look!

https://nextra.site/docs/custom-theme
