### ISSUE TITLE
Customization via custom components

### ISSUE THREAD

**Issue by matteofrana** [shuding/nextra#58]
I think that it's a common requirement to heavily customize the appearance of documentation.
Now I should create a local copy of nextra-theme-docs and customize the style with all the @apply Tailwind directives.
In this way I loose the ability to keep my project updated with nextra-theme-docs new features and the style can become quite messy.

Wouldn't it be better to have nextra-theme-docs more "headless", just creating the structure and accepting as config components for `H1`, `H2`, `SidebarLink` etc?
Since I already have Tailwind in my project, I could create these components already styled and dark-mode ready and pass them to the headless nextra-theme-docs.

What do you think about it?

**Comment by shuding** [comment]
I think the theme can provide some component extensibility, like accepting H1~H2 in the theme config. But for styles, ultimately you will have to write your own CSS to fully customize it. 

So I feel the best way is to import your own CSS inside _app.js, instead of "nextra-theme-docs/style.css" (or you can import and override some styles).

**Comment by matteofrana** [comment]
Thank you, Shu.
