### ISSUE TITLE
Better ways of sorting & naming pages

### ISSUE THREAD

**Issue by gsimone** [shuding/nextra#65]
Hey, I'm enjoying nextra a lot, here's a couple of nitpicks and things I'd like to suggest about sorting & naming.

Right now, order of entries `meta.json` is what sets the order & title of the page. This means that I could name my pages like:

```
01-intro.mdx
02-getting-started.md
03-end.md
```

*This also sorts them correctly in the editor and filesystems*

They'd already be sorted alphabetically in the menu, but I'd still have to manually create a meta.json with the renames.

My proposal is, while leaving everything as is, adding the ability to rename via frontmatter, I noticed that I can use 

```
---
title: Intro
---
``` 
to change the <title /> of the page, it would be convenient if this, or another key, were used to also set the name in the nav.

Thanks anyway for your time and kudos on the project!

**Comment by hmans** [comment]
I would like to also propose that you can control the page's URL slug in a similar manner (IF Next.js allows this, which I'm not 100% sure that it does.)

**Example:** In a file named `10-intro.md`:

---
title: Intro
slug: intro
---

This would serve the page under `/intro` instead of `10-intro`.

**Rationale:** once we start using number prefixes in file names in order to organize the documents using the file system (which is great), we may need to modify these numbers later, and we may not want this to break existing URLs/links.

In fact, Nextra could even go as far as automatically removing number prefixes from the slugs as its default behavior (ie., it could turn `10-intro.md` into `/intro` by stripping the leading `10-`.)

All of this entirely depends on whether Next allows us to change slugs, of course.

**Comment by shuding** [comment]
Thanks for the great suggestions! I agree with both of you that those can be improved. 

Currently there're some technical restrictions that I need to dig a little deeper. For the `meta.json` thing, what I'm thinking about is performance of I/O. Because every page renders the sidebar, which depends on _name and order of all pages_, so to render the sidebar we need to access:
1. structure of the filesystem (recursively readdir)
2. content of all meta.json files (a couple of readfile)

If we store that info (_name and order of all pages_) with frontmatter, we need to access the content of all files. I never did benchmarking but I believe that will become a performance issue when you have many many pages. Although I opened #34 for some related perf improvements, but it seems still very necessary to do some pressure testing. :-)

Regarding the customized `slug`, we need to bypass the restriction of Next.js that "route name === file name", which isn't that easy.

Also personally I'm not a big fan of number based ordering (but I can see how good it organizes the files in the filesystem). Imagine that if want to insert/remove/reorder a page, you'll have to rename many other files to make the numbers look good. With `meta.json` it's much easier.

**Comment by Janpot** [comment]
As an alternative, could it make sense to define the order in the frontmatter of `index.mdx`?

```md
---
order:
- introduction
- installation
- getting-started
- ...
---
```

**Comment by agcty** [comment]
is it possible to order pages already?

**Comment by shuding** [comment]
@agcty You still need to use `meta.json` for that, check [this example](https://github.com/shuding/nextra/blob/master/pages/meta.json).

**Comment by The-Code-Monkey** [comment]
@shuding something ive just noticed is that meta.json doesnt work for files that aren't in the root dir of pages.

e.g. pages/packages/01-thing

it wont get converted by the function that handles meta.

**Comment by PabloLION** [comment]
@The-Code-Monkey  It will work. Notice that this repo has multiple `meta.json` files. Like https://github.com/shuding/nextra/blob/master/pages/themes/meta.json. And you don't need "01-thing" as file name. The pages are ordered like they are in the `meta.json`.

@shuding  Thanks for this great project. I want to ask you: 
1. I didn't see anything about this in the docs (at https://nextra.vercel.app/). Can I make a PR on this? Or you've already worked on it for v2.0 ? 
2. I think a "manifest.json" like https://github.com/vercel/next.js/blob/canary/docs/manifest.json is more extensible. Maybe we can use this in v2 instead of "meta.json"? I've seen that there are other projects using this name like https://github.com/opstrace/next-product-docs. 
3. I don't like the rigid `"routes":[]` syntax in the "manifest.json" in (2.) and putting all routes in one file. So maybe we can support many "manifest.json" as well. The benefit is that with a list of object with `title` and `path`, it's more extensible to add `color`, `font`, `icon`, etc.

**Comment by PabloLION** [comment]
I apologise for not seeing the `meta.json` was mentioned here https://nextra.vercel.app/get-started#sidebar-and-anchor-links. But when I searched meta.json had no result.

**Comment by B2o5T** [comment]
@shuding I think this issue can be closed since no one proposition can propose better impact than meta.json

**Comment by shuding** [comment]
@B2o5T Yep, we don't have a better proposal at the moment. 

One idea I have for future is to open up a UI on dev mode like `vitest --ui` that you can drag and drop to reorder sidebar and menus.

**Comment by B2o5T** [comment]
👍 Closing until better proposal
